### ISSUE TITLE
Request: Hide `placeholder` text in Manual Resolver

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/unfulfilled-rolls#12]
I think the `placeholder` text should be removed/hidden from the user when Manual Rolls is used to help prevent poor sportsmanship, as there is no indication if a die value is manually entered or left empty for the Foundry Roller to resolve

https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/fcacf8ee-254d-4060-b444-b1ae7a51eb74

**Comment by MaxPat931** [comment]
Adding this to styles/unfulfilled-rolls.css seems to do the trick
```css
#manual-resolver .terms .dice-term-input::placeholder {
  opacity:0;
}
```
